development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/development

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/test

production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: db/production
