development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: foodle_development

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: foodle_test

production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: foodle_production
