development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: db/development

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: db/test

production:
 adapter: postgresql
 encoding: utf8
 reconnect: false
 database: db/production
